### ISSUE TITLE
tweakHandRestock bug

### ISSUE THREAD

**Issue by SpodBut** [sakura-ryoko/tweakeroo#14]
Enabling "tweakHandRestock" disables the ability to swap items from your off hand to your main hand.

Steps to Reproduce:
1. Have an item in your offhand
2. Enable "tweakHandRestock"
3. Press vanilla keybind for "Swap Item With Off Hand"

**Comment by sakura-ryoko** [comment]
I'll have it looked into

**Comment by zly2006** [comment]
Please test this version: https://github.com/sakura-ryoko/tweakeroo/actions/runs/9864817945

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-sakura.14
