### ISSUE TITLE
MC 1.21 - blockTypeBreakRestriction is not working

### ISSUE THREAD

**Issue by KominoStyle** [sakura-ryoko/tweakeroo#18]
Im not sure if its only the ListType or if it is the Black and Whitelist, since neither black nor whitelist works

**Comment by sakura-ryoko** [comment]
This fix will take up more of my time, I'll check it out later.

**Comment by sakura-ryoko** [comment]
As far as my testers have shown and reported that this feature works as intended.  It must be a mod conflict or something that you may be having.

**Comment by KominoStyle** [comment]
Okay, well i will look next weekend into it, with wich mod it has conflicts since I barely have different mods than.in 1.20.2.

But i will be home on next Saturday,

**Comment by KominoStyle** [comment]
I Tested it now only with Tweakeroo Mod:
![javaw_J8hp8CV13H](https://github.com/user-attachments/assets/203dd881-092e-4dd6-a381-f0943c9f462b)

This is my Setting for Blacklist:
![javaw_obOZYn6J07](https://github.com/user-attachments/assets/21f5d18c-56a6-48c6-9c82-1fd19f6ef2c7)

This is the Version:
![javaw_xJmwijl0xK](https://github.com/user-attachments/assets/641e62a3-d610-458d-8a5f-82725edcf991)

and this is a gif to show how that the budding_amethyst breaks even if blacklist is on:
https://puu.sh/KbiFZ/2c37e4e909.gif

**Comment by Ka1nnn** [comment]
> I Tested it now only with Tweakeroo Mod: ![javaw_J8hp8CV13H](https://private-user-images.githubusercontent.com/91426727/350677568-203dd881-092e-4dd6-a381-f0943c9f462b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NjgtMjAzZGQ4ODEtMDkyZS00ZGQ2LWEzODEtZjA5NDNjOWY0NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTYyNjYzZjk2NzZlMDg5YzJjNDYxMmIwNzg2ODdhYTJkOTZmZTEzZjhlNTQxNmY4YzRjNGM5OTJiYmY3NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADqZFJP9FOglsOg6RSMUiMqAHFO8GZQ88O1Zyut2hk4)
> 
> This is my Setting for Blacklist: ![javaw_obOZYn6J07](https://private-user-images.githubusercontent.com/91426727/350677573-21f5d18c-56a6-48c6-9c82-1fd19f6ef2c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NzMtMjFmNWQxOGMtNTZhNi00OGM2LTljODItMWZkMTlmNmVmMmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWZhMDU4NTVmNzVhMjMyNmNlOWVlYWYxM2ExNjc5YmYzOWU3YmEzY2Q5NDNiYWFiNjY1ZmI5MzEyNTBhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APNwp2CcUf0hJz3wBgatp2fhXQAvCep5YBMfxB6VX2g)
> 
> This is the Version: ![javaw_xJmwijl0xK](https://private-user-images.githubusercontent.com/91426727/350677574-641e62a3-d610-458d-8a5f-82725edcf991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NzQtNjQxZTYyYTMtZDYxMC00NThkLThhNWYtODI3MjVlZGNmOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODNiYjM0MzY2MmJjNWIwMmM3ZjhmYTA3MDNkZTI1NjU3ODUzN2YwMmU0MmJhZGM0YzgzYWMzNzYwYWE3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mkl2Ydl4xPkDa9ZmrKS0KQAE3lWWuHcNbeBtOD5mhLs)
> 
> and this is a gif to show how that the budding_amethyst breaks even if blacklist is on: https://puu.sh/KbiFZ/2c37e4e909.gif

My bro... Do you even have the tweak enabled?? 

https://i.vgy.me/0s9Bum.png

is this on?

**Comment by KominoStyle** [comment]
> > I Tested it now only with Tweakeroo Mod: ![javaw_J8hp8CV13H](https://private-user-images.githubusercontent.com/91426727/350677568-203dd881-092e-4dd6-a381-f0943c9f462b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NjgtMjAzZGQ4ODEtMDkyZS00ZGQ2LWEzODEtZjA5NDNjOWY0NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTYyNjYzZjk2NzZlMDg5YzJjNDYxMmIwNzg2ODdhYTJkOTZmZTEzZjhlNTQxNmY4YzRjNGM5OTJiYmY3NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADqZFJP9FOglsOg6RSMUiMqAHFO8GZQ88O1Zyut2hk4)
> > This is my Setting for Blacklist: ![javaw_obOZYn6J07](https://private-user-images.githubusercontent.com/91426727/350677573-21f5d18c-56a6-48c6-9c82-1fd19f6ef2c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NzMtMjFmNWQxOGMtNTZhNi00OGM2LTljODItMWZkMTlmNmVmMmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWZhMDU4NTVmNzVhMjMyNmNlOWVlYWYxM2ExNjc5YmYzOWU3YmEzY2Q5NDNiYWFiNjY1ZmI5MzEyNTBhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APNwp2CcUf0hJz3wBgatp2fhXQAvCep5YBMfxB6VX2g)
> > This is the Version: ![javaw_xJmwijl0xK](https://private-user-images.githubusercontent.com/91426727/350677574-641e62a3-d610-458d-8a5f-82725edcf991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzEwOTYsIm5iZiI6MTcyMTQ3MDc5NiwicGF0aCI6Ii85MTQyNjcyNy8zNTA2Nzc1NzQtNjQxZTYyYTMtZDYxMC00NThkLThhNWYtODI3MjVlZGNmOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODNiYjM0MzY2MmJjNWIwMmM3ZjhmYTA3MDNkZTI1NjU3ODUzN2YwMmU0MmJhZGM0YzgzYWMzNzYwYWE3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mkl2Ydl4xPkDa9ZmrKS0KQAE3lWWuHcNbeBtOD5mhLs)
> > and this is a gif to show how that the budding_amethyst breaks even if blacklist is on: https://puu.sh/KbiFZ/2c37e4e909.gif
> 
> My bro... Do you even have the tweak enabled??
> 
> https://i.vgy.me/0s9Bum.png
> 
> is this on?

Thank you, it was not on, now it works but its confusing...
because in the breaking-list, we can choose Black-List, White-List, and None... so i was thinking None is OFF and the others will Activate it.

**Comment by sakura-ryoko** [comment]
That is not the case of any tweak.  The Item Lists are just that, the Black / White List.  If you want the feature(s) on, you need to enable the tweak, and /or set a keybind.
