### ISSUE TITLE
[BUG] Elytra swaps when swimming

### ISSUE THREAD

**Issue by ARedstoneMan** [sakura-ryoko/tweakeroo#19]
Bug: when swimming and pressing space, the elytra is equipped.
Expected behavior: swimming has nothing to do with flying, so the elytra should not be equipped when pressing space underwater. you can't even start flying until you resurface anyway. this is annoying when for example you are trying to collect sponges as without a chestplate you will take a lot more damage from guardians.

bug was experienced in sakura.14, but I assume the bug still persists because nothing about the elytra swap was mentioned in the changelog for sakura.15

EDIT: I should note that it also affects trying to swim out of lava when sinking in it, which can be deadly.

**Comment by sakura-ryoko** [comment]
This will be fixed under tweakeroo sakura.16

**Comment by ARedstoneMan** [comment]
Even in sakura.16, it will not prevent swapping when in lava, making it harder to get out as you are in elytra flight mode and you take more damage. Although I'm not sure if it's worth adding a patch for this, but might as well.

Suggestion: make swapping only occur when jumping from solid ground, or add it as a separate tweak.
