### ISSUE TITLE
MC 1.21 | Having Tweakeroo installed on the server (ie; playing in singleplayer) makes the max_stack_size component not work.

### ISSUE THREAD

**Issue by blockerlocker** [sakura-ryoko/tweakeroo#20]
As title says, giving yourself an item with a custom max_stack_size component will result in the item still being stackable to its default value. The following command gives a piece of stone that can't be stacked in vanilla, but can be stacked with Tweakeroo installed:

`/give @s stone[minecraft:max_stack_size=1]`

**Comment by sakura-ryoko** [comment]
Tweakeroo uses whichever value that is detected that is higher.  If the max_stack_size component is used below the vanilla values is why this would occur.

It is currently coded in such a manner so as to allow people to set the max_stack_size higher without tweakeroo interfering with that.  But a lower value than vanilla?  What ever for ?

That would make the code ever more complex, where taking into consideration the max_stack_size, and returning whichever is higher is more code than it had originally.

**Comment by sakura-ryoko** [comment]
See latest release: https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-sakura.17
