### ISSUE TITLE
tweakToolSwitch/自动切换工具

### ISSUE THREAD

**Issue by G-Lemon** [sakura-ryoko/tweakeroo#21]
关于tweakeroo的自动切换工具，竹子的有效工具是剑而非斧

**Comment by sakura-ryoko** [comment]
I don't think the 'effective' tool for bamboo is an issue since you can break it with your hands almost instantly; but it could probably be investigated.

**Comment by G-Lemon** [comment]
由wiki可以得知"挖掘竹子的合适工具是斧和剑。竹子被剑挖掘时会立刻被破坏。没有工具可以加速对竹笋的挖掘。"
According to the wiki, "The suitable tools for digging bamboo are axes and swords. When bamboo is dug by a sword, it will be immediately destroyed. There is no tool to accelerate the digging of bamboo shoots."

**Comment by zly2006** [comment]
Another bug: 
![image](https://github.com/user-attachments/assets/c395d663-4ab9-4794-978c-c26c5b651f2d)
when toolSwapBetterEnchants is enabled, tweakeroo is ignoring which is the best tool, only switch to the one with best enchantments

**Comment by sakura-ryoko** [comment]
Yeah the code was supposed to ignore that setting and work in the original manner, as the 'Better Enchants' was still experimental

**Comment by sakura-ryoko** [comment]
Please test out https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-sakura.17

**Comment by sakura-ryoko** [comment]
@G-Lemon --> Have you had the chance to test out the current iteration of these features?
