### ISSUE TITLE
[Feature Request] Elytra Swap tweak

### ISSUE THREAD

**Issue by ARedstoneMan** [sakura-ryoko/tweakeroo#25]
A few days ago I opened issue #19 which outlined an issue that should not happen where the elytra is toggled when swimming. Well, I realized while going netherite mining the other day that the elytra is toggled even when "swimming" or sinking in lava. This is quite deadly/annoying without fire resistance when trying to drain lava or escape it because you are put in flight mode which makes it hard to swim out and forces you to use rockets, which may not be ideal. Now, I'm not sure if or how this is supposed to work, but it would be nice to see some extra safety detection system coded in so the elytra doesn't open when in liquids at all, etc. to ensure that it only opens when you intend it to. Overall, you can notice that sometimes the elytra doesn't exactly do what you intend it to do, but these niche scenarios are really only noticed when you play survival with the tweak on constantly. However, I do realize that it's just the nature of the tweak that just makes it clunky.

**Comment by sakura-ryoko** [comment]
I'll talk to zly about it, and for now, I would recommend disabling the tweak while netherite mining

**Comment by sakura-ryoko** [comment]
A fix is slated for sakura 18

**Comment by sakura-ryoko** [comment]
See: https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-sakura.18
