### ISSUE TITLE
tweakNoBlockBreakCooldown should be in Yeets?

### ISSUE THREAD

**Issue by morgantic** [sakura-ryoko/tweakeroo#31]
As the title states, I would have expected the NoBlockBreakCooldown to show up in Yeets, but it's a tweak. This is a bit of a confusing categorization imo.

**Comment by sakura-ryoko** [comment]
Moved to `disableBlockBreakCooldown` under sakura.19

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-sakura.19
