### ISSUE TITLE
[Feature Request] Allow to scroll to change the periodicAttackInterval

### ISSUE THREAD

**Issue by morgantic** [sakura-ryoko/tweakeroo#32]
When you hold the hotkey for PlacementGrid, you can scroll to change the grid size.

It would be very convenient to have the same functionality for changing the periodicAttackInterval when holding the  tweakPeriodicAttack hotkey.

I wanted to have a look at this myself but I can't get the project to build, so instead of opening an untested pull request, I'll open this issue as a feature request. I hope it's not more complicated than just copying the existing code from the periodicAttackInterval function (https://github.com/sakura-ryoko/tweakeroo/blob/cebd78c94a37f30230ea86e9590e967382dfb0ae/src/main/java/fi/dy/masa/tweakeroo/event/InputHandler.java#L210)

**Comment by morgantic** [comment]
I got the project to build so I created a PR for this. Sorry if I messed up anything, probably did, not a pro with GitHub....

**Comment by sakura-ryoko** [comment]
Merged.
