### ISSUE TITLE
Replacing older releases breaks links

### ISSUE THREAD

**Issue by josef-dijon** [sakura-ryoko/tweakeroo#36]
Can you please keep older releases for all of Litematica, Tweakaroo, MiniHUD, Servux, and Malilib?

I have a minecraft server loadout that is linked to a particular version (becuase I've had problems with mods updating themselves in the past) of all mods. Out of ~120 mods installed, these five are the only ones that keep having their github release links broken :)

**Comment by sakura-ryoko** [comment]
Use masa's official versions when he releases them for links.

**Comment by morgantic** [comment]
If you just need the lastest version, you can curl https://api.github.com/repos/sakura-ryoko/tweakeroo/releases/latest and jq .assets.[0].browser_download_url - that's how I semi-auto update mine for the time being. 

EDIT: syntax error
