### ISSUE TITLE
Minor incompatability with Data Driven Stack Sizes

### ISSUE THREAD

**Issue by HydraheadHunter** [sakura-ryoko/tweakeroo#37]
Hello, good day. 

I'm an amataur mod dev making small-changes mods to suit my fancy, and I love using tweakeroo.

I have run into a minor incompatability issue between one of my mods, and tweakeroo which I do not know how to resolve by myself, but I'm hoping you're willing to help in fixing (No problem if no).

The mod, [Data Driven Stack Sizes](https://modrinth.com/mod/data-driven-stack-sizes) ([repo](https://github.com/HydraheadHunter/Data-Driven-Stacks/issues/9)) is meant to override minecraft's default stack sizes with data-driven stack sizes. This is meant to allow datapack makers to both buff an item ability to stack, up to 2048 or nerf it down to 1.

Buffing stack sizes works fine. The incompatability is in nerfing stack sizes. I believe this incompatability is most likely caused by `mixin.MixinItemStack#getMaxStackSizeStackSensitive(cir)`, overriding the return value of `ItemStack.getMaxCount()` through a `Math.max()` call.

As I don't know what feature this override exists inside tweakeroo to facilitate, I feel I cannot just safely remove it. and that my best and only course of action is to request a compatability consideration from you.

Thank you for your time.

**Comment by sakura-ryoko** [comment]
Have you updated tweakeroo ?  This item has been fixed previously, and this is designed to allow Empty Shulkers to stack.

Carpet Mod has a similar functionality.

**Comment by HydraheadHunter** [comment]
The version of tweakeroo I'm experiencing the compatability issue with is `tweakeroo-fabric-1.21-0.20.999-sakura.18.jar` If that is not the most current one, I'm sorry for wasting your time with solved problems.

**Comment by HydraheadHunter** [comment]
Well, I replaced my `tweakeroo-fabric-1.21-0-20-999-sakura.18.jar` with a fresh one. The new one yelled at me that malilib was out of date (in a way the old one hadn't: I just have that magic touch with computers, yeah) so I updated that too, and now the issue's appears to be resolved. 

Thank you for your time, sorry for the bother.
