### ISSUE TITLE
tweakZoom tweak not working

### ISSUE THREAD

**Issue by Sar4h-3** [sakura-ryoko/tweakeroo#39]
versions: 
Minecraft 1.21
fabric 0.15.11
tweakeroo 0.20.999-sakura-20 
malilib 0.20.2

When activating `tweakZoom` , neither the FOV nor the mouse sensitivity get changed, even with `zoomAdjustMouseSensitivity` set to true. I also don't get any error message in the logs. Changing the FOV with the scroll wheel also doesn't fix this. 
I tested this with only tweakeroo and malilib installed.

**Comment by sakura-ryoko** [comment]
Check your advanced keybind settings

**Comment by Sar4h-3** [comment]
Oh, the tweak gets activated at least according to the small message above the hotbar and the tweakeroo settings menu, but it doesn't do anything. So there might be a missing connection between the activation and actually doing what the tweak says.

**Comment by sakura-ryoko** [comment]
Did you bind the Zoom keybind ?

**Comment by Sar4h-3** [comment]
Ah, I thought that the `tweakZoom` key also activated the zoom. I didn't know that there was a key to actually trigger the zoom. It's working fine, I should have remembered to actually check the hotkey tab for a key for this.
