### ISSUE TITLE
[Suggestion] Porting another mod

### ISSUE THREAD

**Issue by KiberAndy** [sakura-ryoko/tweakeroo#40]
I saw this line and got an idea: "Tweakeroo is a client-side-only Minecraft mod using LiteLoader"

Can you port this wonderful mod to Fabric 1.21? 
Macro / Keybind Mod:
https://www.youtube.com/watch?v=qMVEtMlkFNc

I can't find the code for this mod, but here is the mod itself:
[mod_macros_0.15.4_for_1.12.1.zip](https://github.com/user-attachments/files/16398797/mod_macros_0.15.4_for_1.12.1.zip)

**Comment by sakura-ryoko** [comment]
Unrelated to tweakeroo

**Comment by KiberAndy** [comment]
> Unrelated to tweakeroo

I don’t know how to write to you in PM...
