### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LuoliiQaQ** [sakura-ryoko/tweakeroo#41]
The tool automatically switches to the appropriate tool. When holding down the left button and not moving it, assuming there is a long stone in front of you, with stones all up, down, left, right, and right, holding it down is very likely to easily switch to the first grid of the item list. For example, if the manuscript is in 2 or something else, it is not 1, and 1 is any arbitrary thing. If he keeps holding it down, it is easy to switch to 1 and then switch frantically to 2

**Comment by sakura-ryoko** [comment]
If you have issues with the `tweakToolSwitch` I'd recommend disabling it when it is not needed.

**Comment by LuoliiQaQ** [comment]
> The tool automatically switches to the appropriate tool. When holding down the left button and not moving it, assuming there is a long stone in front of you, with stones all up, down, left, right, and right, holding it down is very likely to easily switch to the first grid of the item list. For example, if the manuscript is in 2 or something else, it is not 1, and 1 is any arbitrary thing. If he keeps holding it down, it is easy to switch to 1 and then switch frantically to 2该工具会自动切换到适当的工具。当按住左键而不移动它时，假设你面前有一块长长的石头，石头都是上、下、左、右、右，按住它很可能很容易切换到项目列表的第一个网格。例如，如果手稿在 2 或其他事物中，则它不是 1，而 1 是任意事物。如果他一直按住它，很容易切换到 1，然后疯狂地切换到 2
