### ISSUE TITLE
Newer Versions of Tweakeroo Conflict with Item Scroller Craftfix

### ISSUE THREAD

**Issue by Falsus2** [sakura-ryoko/tweakeroo#45]
Tweakeroo version sakura 16 works completely fine with 1.21 item scroller craft fix found here: https://github.com/CrazyHPi/itemscroller-crafting-fix/releases/tag/1.2.8.121. Using the lastest version of tweakeroo, it no longer functions as intended. Not sure which version caused the issue because I can only test versions 16 and 23. Specifically, the issue is mass crafting not crafting at the intended pace, will be much slower and looks like normal crafting.

**Comment by sakura-ryoko** [comment]
Try it without Tweakeroo if you are complaining about Tweakeroo.

**Comment by sakura-ryoko** [comment]
The 'Only relevant change' that could effect craft fix is:
```
(sakura.17)

    fix getMaxCount() for stacking shulker boxes so it interferes less with other mods.
    fix for Tool Swapping for Bamboo (More testing will be needed)
    Bump for Gradle 8.9, Loom 1.7, FAPI 100.7 / malilib sakura.8
```
Which means that craft fix would need to be updated potentially to accept the updated code for `getMaxCount()` which is only related to Shulker boxes.

**Comment by sakura-ryoko** [comment]
And yet again, I will restate that this is not a Tweakeroo problem; as craft fix would need to be fixed to conform.

**Comment by Falsus2** [comment]
> Try it without Tweakeroo if you are complaining about Tweakeroo.

Just tested, same problem is present without tweakeroo installed. Continues to work with sakura 16 still

**Comment by Falsus2** [comment]
> And yet again, I will restate that this is not a Tweakeroo problem; as craft fix would need to be fixed to conform.

Ah okay, should I open an issue on the craft fix page instead?

**Comment by sakura-ryoko** [comment]
Yup!
