### ISSUE TITLE
Silk Touch preference

### ISSUE THREAD

**Issue by meza** [sakura-ryoko/tweakeroo#46]
Hey, thanks for adding my thing.

Apparently the way you modified the Silk Touch detection doesn't actually work so now the feature doesn't work in the latest version (1.21-sakura-24)

Should I submit a PR to fix it?

**Comment by sakura-ryoko** [comment]
It worked fine in my own testing, and I will not be available to do any PR work this week.

**Comment by meza** [comment]
Interesting! It works if I run the client from the source but doesn't on the SMP. Let me dig and find the cause

**Comment by meza** [comment]
Yeah, it doesn't work in multiplayer settings. Mine does and I'm not sure what the differences are, it makes very little sense :D

**Comment by meza** [comment]
Yup, this makes it work in multiplayer settings too.
I hate this change for 1,21 so much... I was really hoping yours would work

```java
                if (
                    EnchantmentHelper.hasAnyEnchantmentsIn(testedStack, EnchantmentTags.PREVENTS_BEE_SPAWNS_WHEN_MINING)
                    && !EnchantmentHelper.hasAnyEnchantmentsIn(previousTool, EnchantmentTags.PREVENTS_BEE_SPAWNS_WHEN_MINING)
                )
```

**Comment by sakura-ryoko** [comment]
I revisited this, and in my own testing it works just fine on a server without any changes.
I even added a bee_nest to the list, and it switched to a silk touch iron axe.

**Comment by meza** [comment]
Curious! Let me get others on the server test it and see. For me it's very deterministically not working on the server :(

**Comment by meza** [comment]
Yup, it works now with the newest release! I wonder if I had an outdated malilib or something... Very strange.
Thanks for sticking with me 😅
