### ISSUE TITLE
Bug:flexible placement doesnt work when placing crafter

### ISSUE THREAD

**Issue by CloudBack0601** [sakura-ryoko/tweakeroo#47]
when i hold hotkey set to toggle flexible placement to place a crafter facing left ,it always turn to my side（flexible placement doesnt work）. And whatever the side i place it finally turns to me

**Comment by sakura-ryoko** [comment]
The crafter rotations requires accurateBlockPlacement (Easy Place) V3 on the server side that currently can only be provided by Servux 0.3.x+

**Comment by CloudBack0601** [comment]
> The crafter rotations requires accurateBlockPlacement (Easy Place) V3 on the server side that currently can only be provided by Servux 0.3.x+

I did as u said .but it still didnt work.otherwise,blocks like observer  and hopper can be placed every side

**Comment by sakura-ryoko** [comment]
There were several Tweakeroo versions back that fixed the Crafter issues; so I would also suggest making sure that you are using the most recent version of Tweakeroo.

**Comment by CloudBack0601** [comment]
> There were several Tweakeroo versions back that fixed the Crafter issues; so I would also suggest making sure that you are using the most recent version of Tweakeroo.

0.20.999 sakura.9

**Comment by CloudBack0601** [comment]
> > There were several Tweakeroo versions back that fixed the Crafter issues; so I would also suggest making sure that you are using the most recent version of Tweakeroo.
> 
> 0.20.999 sakura.9 

I tried newest version,it works normally
