### ISSUE TITLE
Translation display error

### ISSUE THREAD

**Issue by BlackRiceXY** [sakura-ryoko/tweakeroo#50]
1.21-sakura.24 does not display Chinese properly in 1.21.1

**Comment by sakura-ryoko** [comment]
Tweakeroo doesn't have a Chinese translation file.
Since, I cannot speak Chinese, I cannot translate it myself; I would need someone else to offer the PR for it.

**Comment by Phoupraw** [comment]
I hear that the current translation work is done on crowdin? How can I contribute translations?

**Comment by sakura-ryoko** [comment]
If you wish to translate Tweakeroo, I can attach for you the 'existing' crowdin file that needs work This is both the "Simplified" and "Traditional" files:

[zh_cn.json](https://github.com/user-attachments/files/17969363/zh_cn.json)
[zh_tw.json](https://github.com/user-attachments/files/17969362/zh_tw.json)

**Comment by Phoupraw** [comment]
Should I open a PR? Or just post modified lang file here?

**Comment by sakura-ryoko** [comment]
If you can do a PR, that works easiest.

**Comment by sakura-ryoko** [comment]
Also for Tweakeroo, I have added all of the 'prettyName' entries to the en_us.json since these two files; but I don't think that they are required, unless you want the 'prettyName' to be controllable for translation for the `Yeets` toggles.

See the current repo's `en_us.json` to see those.
