### ISSUE TITLE
[Bug] 开启禁用方块破坏冷却后创造模式错误

### ISSUE THREAD

**Issue by AbroadSphere** [sakura-ryoko/tweakeroo#53]
开启禁用方块破坏冷却后会使创造模式的破坏冷却也被移除，出现点一下左键破坏多个方块

**Comment by vocaloidkiss** [comment]
同，建议玩家在创造模式时无效化

**Comment by vocaloidkiss** [comment]
@sakura-ryoko

**Comment by sakura-ryoko** [comment]
See next release https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-0.21.1-sakura.1
