### ISSUE TITLE
Tweak for old bundle tooltip/preview, but with new mechanics like the scrolling

### ISSUE THREAD

**Issue by TQNL** [sakura-ryoko/tweakeroo#58]
![image](https://github.com/user-attachments/assets/8df2d5fd-814a-47c9-a442-d7e1ff2d4c49)
This is the old bundle UI. my request 'enhancement' is that this UI could be toggled for the upcoming 1.21.2 with a new tweak, while retaining the new functionality. The old UI looks a lot like the shulker box preview, shows all items, and looks much cleaner imo.

**Comment by sakura-ryoko** [comment]
Check out https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21.3-0.22.0-sakura.4 for 1.21.3 .

**Comment by sakura-ryoko** [comment]
The result is somewhat like you have suggested.  Holding Shift 'disables' the Vanilla tool tip, and shows the MaLiLib based one.  See the screen shot., and if you disable the `RequiresShift` for it, then it completely disables the new Vanilla one, and replaces it with this one.

![2024-11-02_17 04 46](https://github.com/user-attachments/assets/e2fe40aa-0bf5-4712-96d6-ae579f91164e)

It also changes the colors based on the color of the Bundle, just like the Shulker Box Display.  It adds rows every 9 items, to look familiar with the existing layouts; it just scales as the bundle gets filled.

The Screen Shot is from MiniHUD, but I also copied the code to Tweakeroo.

**Comment by TQNL** [comment]
:O I like it. Of course, it's not completely the old UI, but I will definitely have this enabled :)
