### ISSUE TITLE
Using ElytraCamera crashes game

### ISSUE THREAD

**Issue by kkellogg378** [sakura-ryoko/tweakeroo#62]
Just updated to Tweakeroo-1.21.1-0.21.52. Now pressing the toggle for elytraCamera instantly crashes the game

Side note: PlayerInventoryPeek on tweakaroo also causes an identical crash, but I'm just able to use the InventoryPreview in MiniHUD as a replacement, 

[crashlog.txt](https://github.com/user-attachments/files/17693683/crashlog.txt)

**Comment by sakura-ryoko** [comment]
Disable Masa Gadget and try again

**Comment by sakura-ryoko** [comment]
There were several code changes that they are trying to MIXIN to, which have changed, and the source of the crash; so they'll need to adapt their code to work with 0.21.51 and above.

**Comment by sakura-ryoko** [comment]
```
[19:19:39] [Render thread/ERROR]: Mixin apply for mod masa_gadget_mod failed masa_gadget_mod.mixins.json:mod_tweak.tweakeroo.inventoryPreviewSupportPlayer.MixinRenderUtils from mod masa_gadget_mod -> fi.dy.masa.tweakeroo.renderer.RenderUtils:
<SNIP>
```

They will need to update whatever they are trying to do with inventoryPreview, because the InventoryPreview has been pretty much re-written for this version.

**Comment by kkellogg378** [comment]
After disabling masa gadget, the game still crashed, so I tried disabling tweakermore as well (modified to remove tweaks.mod_tweaks.serverDataSyncer.minihud.RenderHandlerMixin) and that fixed it. Guess both mods need updated
