### ISSUE TITLE
Translation of tweakeroo.config.generic.prettyName.freeCameraPlayerMovement appears to be forgotten when using a keybind to toggle it

### ISSUE THREAD

**Issue by davie53** [sakura-ryoko/tweakeroo#70]
The title.

![2024-11-21_16 04 27](https://github.com/user-attachments/assets/c7c5c43b-cb19-47b9-a148-9d80dfd45c2f)

**Comment by sakura-ryoko** [comment]
Translations should be fixed in the Modrinth release.
