### ISSUE TITLE
When auto switch elytra is on, if you hold down jump the elytra are worn

### ISSUE THREAD

**Issue by Nitroghast** [sakura-ryoko/tweakeroo#76]
As per the title, if auto-switch elytra is on and you hold down space while sprinting, the mod thinks you are falling and puts on the elytra. I think the issue might be in how the mod checks if the player is falling and wants to open the elytra: I looked into the mod files, and it cares if jump is pressed rather than whether it has been tapped (it worked fine in the version for MC 1.21), and also the elytra only activate if the player is going forward for some reason. Again, this wasn't an issue in the version for 1.21.

**Comment by sakura-ryoko** [comment]
That is the intended behavior.  Just by "Jumping" it should equip the Elytra.

**Comment by Maeh-Kun** [comment]
Oh so it is not a bug... Hope this doesnt sound to demanding but I would say splitting it into 2 Tweaks would make more sense. For me the new Version doesnt rly make sense to use because i walk around 90% with my elytra on... I rly loved how the Tweak worked in 1.21 and would do anything to get an option to use the old Version of it again. I dont know how others feel about it just wanted to give Feedback from my side. Ty for making Mods like this available for us tho...

**Comment by Nitroghast** [comment]
> Oh so it is not a bug... Hope this doesnt sound to demanding but I would say splitting it into 2 Tweaks would make more sense. For me the new Version doesnt rly make sense to use because i walk around 90% with my elytra on... I rly loved how the Tweak worked in 1.21 and would do anything to get an option to use the old Version of it again. I dont know how others feel about it just wanted to give Feedback from my side. Ty for making Mods like this available for us tho...

Yea, the old version was better, it would make more sense if the elytra were only equipped when you tried to use them, you don't need them everytime you jump, only when you "double jump". Thanks for making these mods

**Comment by sakura-ryoko** [comment]
Understood, but the change was due to vanilla changes; so the way that the mod would detect that has changed.  I can take another look at it some time; but I made it like this for now, or else I would have needed to remove it.

**Comment by sakura-ryoko** [comment]
See : https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21.4-0.23.0-sakura.7
