### ISSUE TITLE
screen wrong

### ISSUE THREAD

**Issue by 18895kmxk** [sakura-ryoko/tweakeroo#77]
look at right，what happen？what can i do？
![屏幕截图 2024-12-01 195417](https://github.com/user-attachments/assets/43432b7f-6092-46c1-bd0a-cb2fdfbd77c7)

**Comment by sakura-ryoko** [comment]
This is a screen GUI Scale issue.  You can got into the Vanilla Video settings, and adjust the GUI Scale size if you want to use windowed mode like this.

**Comment by sakura-ryoko** [comment]
I actually found a bug related to this.  Will be in the next updates.
