### ISSUE TITLE
The GUI of version 1.21.1_21.54 shows an error

### ISSUE THREAD

**Issue by BerryMC** [sakura-ryoko/tweakeroo#83]
![image](https://github.com/user-attachments/assets/0a3bce3d-a4ca-4c89-b23c-d1cbf06ad2f1)
![image](https://github.com/user-attachments/assets/0418902e-b9a8-4ad1-93a1-452fd76e0519)
My screen resolution is 1920x1080
(I'm using a translation tool)

**Comment by sakura-ryoko** [comment]
This has already been fixed under the sakura 0.21.55-sakura.X versions
