### ISSUE TITLE
bug:press space once would cause the player to jump and equip elytra when tweakAutoSwitchElytra is on.

### ISSUE THREAD

**Issue by Prohect** [sakura-ryoko/tweakeroo#84]
simply press space and not release would let the player jump which is expected, and, when option tweakAutoSwitchElytra is on, equip elytra, which is not expected. expect:press and release space once, the player jump. when player is jumping in the air and u had released space and repress space, then switch chest slot to elytra and fly.

**Comment by Prohect** [comment]
I've fix it: https://github.com/Prohect/tweakeroo/commit/befed3235089fc621f6525f9cbeb68f497db534e
https://github.com/Prohect/tweakeroo/commit/b63a1d0cf9d0c87fc51591f4bf7b7231800452cb
I'm not administractor of this depository. so i forked it and tried solve it;

**Comment by Prohect** [comment]
由于更新了settings.gradle,添加了accesswidener，需要在gradle里面重新执行gensources，才不会报错越权访问

**Comment by sakura-ryoko** [comment]
Writing a PR is always an option.

**Comment by Prohect** [comment]
PR on the way

**Comment by sakura-ryoko** [comment]
This in general really isn't a bug per-se; BUT it was mostly a regression based on Vanilla changes to how the "is Fall Flying" is calculated.  In fact, the code that used to allow for this tweak to work the way it used to was removed from the game.

**Comment by sakura-ryoko** [comment]
To be clear also; I still intend to take yet another 5th (or so) look at this code; I just haven't yet.

**Comment by zly2006** [comment]
On minecraft 1.21.2-1.21.4, Press jump and walk at the same time would cause elytra be swapped on. This is because mojang's data driven changes, and related changes to fall flying/gliding. And there is a better way to fix it, thanks for your contribution!

**Comment by sakura-ryoko** [comment]
See : https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21.4-0.23.0-sakura.7
