### ISSUE TITLE
[Bug] Enable "tweakAccurateBlockPlacement" and "tweakFlexibleBlockPlacement", but I cannot place flexibly

### ISSUE THREAD

**Issue by Piscescup** [sakura-ryoko/tweakeroo#86]
After enabling the configs "tweakAccurateBlockPlacement" and "tweakFlexibleBlockPlacement" in the tab "tweaks", I place directional blocks, such as piston, observer, crafter and so on. The blocks can not place correctly. They will be placed following the default placement behavior of vanilla Minecraft.
![Sticky Piston 1](https://github.com/user-attachments/assets/342143ea-044f-472c-9316-20725ed1f210)
![Sticky Piston 2](https://github.com/user-attachments/assets/86f40c37-b96f-44d0-b978-62a8bf0bade5)

**Comment by sakura-ryoko** [comment]
Does your Server have accurate Block Placement / Easy Place enabled ?
This is the expected behavior when the server does not support it.

**Comment by Piscescup** [comment]
Ok， the issue is solved after enable the "easyPlace"

**Comment by sakura-ryoko** [comment]
Nice font also.  lol.
