### ISSUE TITLE
Feature Request: Unlock left click while shielding 

### ISSUE THREAD

**Issue by kkellogg378** [sakura-ryoko/tweakeroo#91]
It would be neat if there was a simple toggle called `unlockLeftClickWhileShielding` that allows you to mine or attack while holding right click if a shield is in your offhand

**Comment by qingshu-ui** [comment]
这个功能看起来有点破坏平衡，不过在meteor client和一些hack client已经实现了，如果你游玩的服务器允许，你可以使用这些客户端。

**Comment by kkellogg378** [comment]
Tweakeroo already has many arguably unbalanced features as it is, but if there's multiplayer concern for this particular feature still it could be implemented as a feature that requires Servux with the setting enabled to function in multiplayer

**Comment by sakura-ryoko** [comment]
I don't think this should be in the game, personally.
